const scene = (view, operation, narration) => Object.freeze({ view, operation, narration, ...SEQUENCES[operation] });
const shot = (file, at, label) => Object.freeze({ file: `v2/${file}`, at, ...(label ? { label } : {}) });
const sequence = (shots, stateAt = .62, accidentShots) => Object.freeze({ shots: Object.freeze(shots), stateAt, ...(accidentShots ? { accidentShots: Object.freeze(accidentShots) } : {}) });
const approachRisk = [shot('access-before', 0, '작업 지점'), shot('access-motion', .25, '벨트 움직임'), shot('access-risk', .48, '접근 중 위험 발생')];
const SEQUENCES = Object.freeze({
  'running-reach': sequence([shot('access-motion', 0)], .62, [shot('access-motion', 0, '운전 중인 벨트'), shot('access-risk', .48, '접근 중 위험 발생')]),
  emergency: sequence([shot('control-idle', 0), shot('control-emergency', .28, '비상정지 조작'), shot('control-idle', .78)]),
  stop: sequence([shot('control-idle', 0), shot('control-stop', .28, '정지 조작'), shot('access-before', .66, '벨트 정지 확인')], .66),
  slow: sequence([shot('access-motion', 0, '감속 후에도 움직임 유지')]),
  transmit: sequence([shot('radio-idle', 0), shot('radio-transmit', .25, '대상과 작업 전달'), shot('radio-idle', .8)], .75),
  unused: sequence([shot('radio-idle', 0, '전달하지 않음')]),
  vague: sequence([shot('radio-idle', 0), shot('radio-transmit', .25, '대상과 작업 내용 미확인'), shot('radio-idle', .8)]),
  'unprotected-reach': sequence([shot('access-before', 0, '차단 없이 접근 준비')], .62, approachRisk),
  'other-equipment': sequence([shot('isolator-open', 0, '작업 대상 B/C'), shot('isolator-other-equipment', .35, '다른 설비 A에 잠금')]),
  'other-person': sequence([shot('isolator-other', 0, '타인 잠금만 확인')]),
  'wrong-loop': sequence([shot('isolator-open', 0), shot('isolator-wrong-loop', .4, '차단 조작부와 무관한 문고리에 잠금')], .62, approachRisk),
  lock: sequence([shot('isolator-open', 0, '차단 지점 확인'), shot('isolator-contact', .25, '잠금 지점에 걸쇠 삽입'), shot('isolator-locked', .62, '본인 잠금 체결')]),
  'no-tag': sequence([shot('isolator-locked', 0, '작업 표지 없음')]),
  tag: sequence([shot('isolator-locked', 0), shot('isolator-tag-contact', .25, '작업 표지 부착'), shot('isolator-tagged', .62, '본인 작업 표지 부착')], .62),
  'wrong-name': sequence([shot('isolator-locked', 0), shot('isolator-tag-other', .62, '다른 작업자 이름 표지')]),
  unreadable: sequence([shot('isolator-locked', 0), shot('isolator-tag-worn', .62, '식별 정보를 읽을 수 없음')]),
  unverified: sequence([shot('control-idle', 0, '확인 조작하지 않음')]),
  'failed-test': sequence([shot('control-idle', 0), shot('control-test', .25, '기동 확인 조작'), shot('access-motion', .6, '움직임 발견, 작업 보류')]),
  test: sequence([shot('control-idle', 0), shot('control-test', .22, '기동 확인 조작'), shot('access-before', .48, '무가동 확인'), shot('control-stop', .66, '정지 상태 복귀'), shot('control-idle', .86)], .86),
  'no-return': sequence([shot('control-idle', 0), shot('control-test', .25, '기동 조작 유지, 정지 복귀하지 않음')]),
  remove: sequence([shot('access-before', 0, '확인된 작업 범위'), shot('access-contact', .22, '도구로 이물질 접촉'), shot('access-pull', .48, '이물질을 밖으로 꺼냄'), shot('access-clear', .76, '제거 완료')], .76),
  unlock: sequence([shot('isolator-tagged', 0), shot('isolator-unlock', .3, '작업 전 잠금 해제'), shot('isolator-open', .65, '잠금 보호 해제')], .65, approachRisk),
  outside: sequence([shot('access-before', 0, '확인된 B/C 작업 범위'), shot('access-adjacent', .5, '인접 설비는 확인되지 않아 작업 보류')]),
  'restart-request': sequence([shot('radio-idle', 0), shot('radio-transmit', .25, '재기동 요청'), shot('isolator-tagged', .7, '작업 잠금 유지, 요청 보류')]),
});
export const ACTION_SCENES = Object.freeze({
  'stop-enter-running': scene('access', 'running-reach', '운전 중인 벨트에 손이 접근합니다.'),
  'stop-emergency-only': scene('control', 'emergency', '비상정지를 누릅니다. 정지 표시만으로 차단은 확인되지 않습니다.'),
  'stop-correct': scene('control', 'stop', '정지 버튼을 누르고 벨트가 멈추는 것을 확인합니다.'),
  'stop-slower': scene('access', 'slow', '속도가 줄었지만 벨트는 계속 움직입니다. 접근을 보류합니다.'),
  'notify-correct': scene('radio', 'transmit', '작업자: B/C 컨베이어 이물질 제거 작업입니다. 작업 중 재가동하지 마세요. 오퍼레이터: 대상과 작업 확인했습니다.'),
  'notify-skip': scene('radio', 'unused', '무전기를 사용하지 않았습니다. 작업 전달을 보완해야 합니다.'),
  'notify-vague': scene('radio', 'vague', '작업자: 잠깐 볼게요. 오퍼레이터: 어느 설비에서 어떤 작업인가요?'),
  'notify-enter': scene('access', 'unprotected-reach', '정지했지만 에너지 차단 없이 점검구로 접근합니다.'),
  'lock-other-equipment': scene('isolator', 'other-equipment', '다른 컨베이어의 차단장치에 잠금을 체결했습니다. B/C 대상과 일치하지 않습니다.'),
  'lock-other-person': scene('isolator', 'other-person', '타인의 잠금만 있습니다. 본인 잠금은 체결하지 않았습니다.'),
  'lock-wrong-then-enter': scene('isolator', 'wrong-loop', '차단장치와 무관한 주변 고리에 자물쇠를 겁니다. 차단 조작부는 자유롭게 움직일 수 있습니다.'),
  'lock-correct': scene('isolator', 'lock', 'B/C 대상을 확인하고 차단 조작 후 본인 자물쇠를 체결합니다.'),
  'tag-skip': scene('isolator', 'no-tag', '자물쇠는 있지만 작업자를 식별할 표지가 없습니다.'),
  'tag-correct': scene('isolator', 'tag', '본인의 작업 정보가 담긴 표지를 잠금 지점에 부착합니다.'),
  'tag-wrong-name': scene('isolator', 'wrong-name', '다른 작업자의 이름이 적힌 표지를 붙였습니다.'),
  'tag-unreadable': scene('isolator', 'unreadable', '표지의 식별 정보를 읽을 수 없습니다.'),
  'tryout-skip': scene('control', 'unverified', '확인 조작을 하지 않았습니다. 차단 유효성은 미확인 상태입니다.'),
  'tryout-failed': scene('control', 'failed-test', '확인 조작 중 벨트 움직임을 발견했습니다. 진입을 보류합니다.'),
  'tryout-correct': scene('control', 'test', '잔류 에너지 조치 후 무가동을 확인하고 조작부를 정지 상태로 복귀합니다.'),
  'tryout-no-return': scene('control', 'no-return', '움직임은 없지만 조작부에 기동 지시가 남았습니다. 정지 복귀가 필요합니다.'),
  'cleanup-correct': scene('access', 'remove', '본인 잠금과 표지를 유지한 채 확인된 범위의 이물질을 제거합니다.'),
  'cleanup-unlock': scene('isolator', 'unlock', '작업 전에 본인 자물쇠를 풀었습니다. 차단 유지 보호를 잃었습니다.'),
  'cleanup-expand': scene('access', 'outside', '옆 설비는 확인된 작업 범위 밖입니다. 접근하기 전에 작업을 보류합니다.'),
  'cleanup-restart': scene('radio', 'restart-request', '작업자: 다시 기동해 주세요. 오퍼레이터: 작업 잠금 상태입니다. 요청을 보류합니다.'),
});
export const ACCIDENT_IDS = Object.freeze(['stop-enter-running', 'notify-enter', 'lock-wrong-then-enter', 'cleanup-unlock']);
